server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=10s;

    set $product_upstream http://product-service:4001;
    set $order_upstream http://order-service:4002;

    location /products { proxy_pass $product_upstream; }
    location /categories { proxy_pass $product_upstream; }
    location /cart { proxy_pass $product_upstream; }
    location /orders { proxy_pass $order_upstream; }
    location /payments { proxy_pass $order_upstream; }
    location /auth { proxy_pass $order_upstream; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
